<p>
Antoine Kuoch a 21 ans, son petit frère Thomas, 19. Ils viennent d’un milieu modeste : leur mère est aide-soignante et leur père, sans papiers, n’a pas de revenu. Pourtant, les deux frères ont commencé le golf très jeunes, initiés par leur père. Celui-ci, né au Cambodge, a pratiqué le golf dans ses jeunes années. En France, il a transmis sa passion à ses fils. Thomas et Antoine s’enthousiasment très vite pour ce sport. 
<em>« Mon père a fui la guerre au Cambodge pour la France, sans argent. Il a beaucoup travaillé et est devenu ingénieur ici »</em>, témoigne Thomas.
C’est à cette période que les frères Kuoch pratiquent leur sport de manière intensive, au point de se lancer dans la compétition. À 13 ans, Antoine accède au « pôle espoir » et ainsi, aux compétitions internationales. Pourtant, Antoine et Thomas vivent une situation familiale et financière délicate : <em>« Il n’a pas réussi à renouveler ses papiers. Heureusement qu’on avait le salaire de ma mère parce qu’il ne peut toujours pas travailler »</em>, poursuit Thomas.

</p>

<h3 class="inter"><em>« Il y a quand même des gens sacrément blindés»</em></h3>

<p>
Pour toutes ces raisons, la famille déménage dans un logement moins coûteux et s'éloigne du club de golf. Thomas, le cadet, finit par arrêter le golf à 13 ans, le club le plus proche se trouvant à une heure de route. Étudiant en mathématiques et en physique, il pense tout de même reprendre le golf une fois adulte, mais pas seulement pour l’amour du sport : <em>« Comme c’est un milieu de riches, c’est facile de tisser un réseau de relations professionnelles au golf. C’est pratique »</em>.
Quand son frère est contraint d’arrêter le golf, Antoine a déjà intégré l’équipe de France depuis deux ans et étudie en sport étude au sein du CREPS (Centre de ressources, d'expertise et de performance sportives). <em>« En 2014, j’ai terminé deuxième meilleur joueur européen et 500e mondial, toutes catégories confondues, j’avais 15 ans »</em>. Aujourd’hui étudiant en ingénierie et boursier comme son petit frère, il avoue que son parcours serait difficile à réaliser sans sponsors. Le sien, Titleist, une grande marque de golf, a commencé à financer son matériel avant ses 14 ans : <em>« Quand tu passes professionnel, il y a beaucoup d’argent en jeu sur toi. Tes déplacements sont payés par l’équipe de France et des clubs te paient à titre privé pour venir jouer chez eux »</em>. C’est également de cette façon que Thomas Kuoch a pu pratiquer le golf plus jeune sans trop dépenser, en récupérant le matériel professionnel de son grand frère. <em>« Le matériel était très cher. Je jouais avec ce que je pouvais mais il fallait rapidement passer à la marque. Je rachète d’occasion à mes amis riches du club »</em>, se souvient-il. Pour jouer au golf en compétition de haut niveau, Titleistn a couvert presque 3 000 euros de pratique par an. <em>« Au golf, soit tu as de l’argent, soit tu te fais sponsoriser parce que tu es très bon. Au club, ceux qui n’avaient ni argent ni talent, c’était le centre aéré pour eux »</em>, commente Thomas.

Face à la réputation du golf, comme sport de privilégié⸱e⸱s, les frères Kuoch ne sont pas sur la même ligne. Thomas considère qu’il a eu de la chance dans un monde de privilégié⸱e⸱s qui n’est pas le sien. Antoine, de son côté, tempère : <em>« On m’a tellement répété ces clichés sur les sports de riches ! Je ne les écoute même plus. Je me tais et je ris. Certes, il existe des clubs très élitistes mais cela ne concerne pas une majorité »</em>.
Ces clubs élitistes, Antoine les connaît bien. Un club en particulier l’a marqué au Japon, où il a joué pour les championnats du monde : <em>« Pour jouer dans ce club, tu devais payer 18 millions d’euros l’année et devenir actionnaire du club ! »</em>. Selon Antoine, la majorité des clubs n’est pas élitiste, mais <em>« les gens retiennent ces exemples, il faut bien avoir des histoires à raconter ! »</em>. Il reconnaît toutefois un univers pétri de culture anglo-saxonne et de valeurs traditionnelles. « Il y a quand même des gens sacrément blindés {...} Tu fréquentes des gens que tu ne rencontrerais jamais sinon, tu sens qu’on ne vient pas tous du même monde. » Pour lui, les éléments qui différencient les joueurs⸱es de golf des autres sportif·ve·s, se trouvent davantage dans l’identité liée au sport que dans le portefeuille.

</p>

<h3 class="inter">Un budget annuel de 1 000 €</h3>
<br>
<div style="width: 100%;"><div style="position: relative; padding-bottom: 56.25%; padding-top: 0; height: 0;"><iframe frameborder="0" width="1200px" height="675px" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://view.genial.ly/5fff3f00fbb1810d1572624c" type="text/html" allowscriptaccess="always" allowfullscreen="true" scrolling="yes" allownetworking="all"></iframe> </div> </div>
<p>
Le golf est l’emblème du sport de riche. La Fédération française de golf (FFG) estime le budget annuel nécessaire à la pratique sans compétition autour de 1 000 euros par an, matériel, adhésion et leçons comprises. En comparaison, un⸱e joueur⸱se de rugby amateur⸱trice doit débourser moins de 150 euros par an. Difficile de se défaire de cette image de sport de riche lorsque sa pratique coûte si cher. Le témoignage d’Antoine et Thomas souligne l’entre-soi des golfeurs⸱ses et cette culture qui est si difficile de s’approprier lorsqu’elle n’est pas acquise dès l’enfance.
En 1856, le golf arrive en France avec la construction du premier club à Pau. Selon Jean-Yves Guillain, auteur de Histoire du golf en France : Le temps des pionniers, édité par l’Harmattan, l’influence anglo-saxonne jusqu’à la fin de la deuxième guerre mondiale se voit encore aujourd’hui. <em>« La discipline a gardé les mêmes règlements qu'à sa création, ses règles d’intégration, son profil de joueur, sa sociabilité, son matériel et tenues spécifiques, {...} et ses techniques d’enseignement »</em>. Cet attachement à la tradition rend difficile une réelle ouverture et démocratisation de ce sport.
</p>

<h3 class="inter">L’équitation, quatrième sport le plus pratiqué en France</h3>
<br>
<iframe width='600' height='600' src='https://injep-test.atlasante.fr/?view=map28&indics=lic2017_1fede.nomfede&lang=fr&iframe=1'></iframe>
<p>
Avec ses 644 800 adhérent⸱e⸱s en 2019, l’équitation est le quatrième sport le plus pratiqué en France. Cette discipline, à la fois populaire et élitiste, a vu le nombre de ses licencié⸱e⸱s augmenter en 2020. Selon l’article de Vérène Chevalier, <em>« Pratiques culturelles et carrières d'amateurs : le cas des parcours de cavaliers dans les clubs d'équitation »</em>, publié en 1998, le nombre de licencié⸱e⸱s d’équitation a été multiplié par dix, entre le début des années 1950 et 1988. Aussi, les données de l’Insee, sur lesquelles se base l’auteure, montrent qu’il y avait <em>« parmi les pratiquants de l’équitation plus de diplômés ou de hauts revenus que dans la population française »</em>. Des sur-représentations toutefois moins marquées que vingt ans auparavant.
Un cours d’une heure coûte en moyenne 15 euros, soit pas moins de 500 euros l’année pour un cours hebdomadaire, hors vacances scolaires. Il faut aussi compter entre 100 et 150 euros pour l’entretien du cheval et du matériel. Les stages et les compétitions s’ajoutent à cette somme. C’est d’ailleurs sur ce point que les écarts se creusent. Un tour lors d’une compétition amatrice coûte 15 euros mais le club demande une participation supplémentaire à ses cavaliers⸱ères. Déplacement du cheval, coaching sur place, les compétitions à l’extérieur sont plus onéreuses pour les sportif⸱ve⸱s. Au bout du compte, il faut compter entre 50 et 60 euros pour un tour, puis 15 euros pour chaque nouveau tour, soit près de 75 euros pour un déplacement en compétition pour deux tours. Il s’agit d’un budget conséquent pour celle⸱ux qui sortent en compétition deux à trois fois par mois.
Aussi, un⸱e cavalier⸱ère ne peut se rendre aux championnats de France amateurs⸱trices, à Lamotte-Beuvron s’il n’a pas fait suffisamment de tours classés. Pour être classé⸱e, il faut arriver dans le premier quart du classement lors d’une compétition. Et pour prétendre au titre, il faut valider entre huit et dix tours classés au cours de l’année.
Sans compter le budget qui explose lorsque le club se déplace pour une semaine, dans une autre région. Location de box ou de prés, denrées alimentaires pour le cheval, coaching quotidien, inscription aux multiples catégories sur place, hébergement pour les cavaliers⸱ères : <em>« Comptez minimum 500 euros pour les championnats de France »</em>, explique le club hippique de Saint-Sylvain d’Anjou.
</p>

<h3 class="inter"><em>« En compète, c’est un budget totalement différent »</em></h3>

<p>
Claire, étudiante en troisième année en Langues étrangères appliquées (LEA) souhaite travailler plus tard dans le commerce. Elle a 20 ans et monte à cheval depuis 15 ans, à Verrière-en-Anjou (49). Ses parents gagnent 2 800 euros par mois et se situent entre le septième et le huitième décile de niveau de vie. Les déciles permettent de se faire une idée des niveaux de vie dans la population. Des données utiles à l’Insee. Les ménages sont donc classés par niveau de vie croissant et on les découpe en 10 tranches. Le premier décile correspond aux 10% de ménages les plus pauvres, et le dernier décile correspond au 10% de ménages les plus riches.
 <em>« Je reçois régulièrement des virements de mes grands-parents ce qui me permet, en grande partie, de financer ma pratique »</em>, précise Claire. Après avoir acheté un cheval, elle a opté pour une demi-pension, moins coûteuse. Ainsi, elle paye 50 euros par mois un propriétaire pour venir monter son cheval plusieurs fois par semaine. <em>« Récemment, j’ai acheté une selle d’occasion à 150 euros, un filet neuf à 40 euros et des protections pour le cheval à 40 euros. C’est un achat conséquent sur le moment, mais ça va durer des mois, voire même des années ».</em>
La jeune femme admet qu’il était difficile pour elle de payer la pension de son cheval. Au début, elle payait une pension au pré 200 euros par mois. <em>« C’est énorme et ça coûte très cher »</em>, témoigne-t-elle. Toutes les six à huit semaines, il faut faire venir un⸱e maréchal·e-ferrant·e et régulièrement, un·e vétérinaire. Elle repense notamment à ce jour où elle a dû payer 40 euros un vétérinaire sans qu’il ait eu besoin de toucher son équidé. <em>« En compète, c’est un budget complètement différent et conséquent par rapport au loisir, ajoute-t-elle. Il faut payer les tours plus les cours ».</em>
Elle a participé à quelques-unes des compétitions organisées par son club, mais ne s’est jamais rendue à l’extérieur car l’ambiance ne lui plaisait pas. A cause d’un problème d’intégration ? <em>« Comme je ne suis pas dans le monde de la compétition, je n’ai pas eu de problème d’intégration, mais je pense que pour ceux qui font des compètes, c’est toujours très compétitif ».</em>
</p>

<h3 class="inter"><em>« C’est le licenciement de mon père qui a permis de payer le cheval »</em></h3>

<p>
Passionnée par l’équitation depuis treize ans, Elisa a dû faire face au licenciement de son père, il y a plus d’un an. Ses parents gagnent à elle·ux deux près de 5 000 euros par mois, et se situent dans le dernier décile de la population, soit la tranche la plus riche. « J’en ai à peu près pour 500 euros l’année et je viens de m’acheter un cheval.» Contrairement à Claire, elle n’a pas besoin de payer de pension parce que son cheval est utilisé dans les cours du centre. Il ne reste donc à sa charge que les frais de maréchalerie. « C’est le licenciement de mon père qui a permis de payer le cheval. Sinon, on n’aurait pas pu se le permettre.» Elle ajoute avoir ressenti une certaine rivalité et des regards oppressants émanant des filles du clubs, mais plus depuis qu’elle a son cheval.
Pour rappel, le revenu médian des Français·e·s s'élève à 1 850 euros. Au contraire, le football et ses 1 933 680 licencié·e·s ne nécessite pas autant de budget. La Fédération française de football (FFF) compte à ce jour 400 000 bénévoles. Parmi elle·ux, beaucoup s’impliquent en tant qu’encadrant.e.s dans les petits clubs de campagne. L’année de foot coûte entre 150 et 200 euros par an, soit 60 centimes le cours. Aussi, les déplacements à l’extérieur le week-end sont couverts par le club. La pratique est quasiment gratuite et en prime, elle ne requiert pas d’entretien, si ce n’est l’achat des crampons en début de saison.
Selon un article publié en 2011, “Stratifications sportives et structures sociales”, écrit par Jacques Defrance, le golf, mais aussi le tennis et le ski alpin, sont des disciplines dans lesquelles les cadres supérieur·e·s et patron·e·s, professions libérales et intermédiaires sont surreprésenté·e·s, voire occupent « parfois une position écrasante ».
</p>
<br>
<img src="../img/Capturedecran.png" />

<h3 class="inter">8 000 euros pour passer le permis avion </h3>

<p> Même combat dans le monde de l’aviation et des sports automobiles plus généralement. Flavien a 19 ans et suit une formation privée de pilote d’avion pour en faire son métier. Jusqu’ici, ce sont ses parents qui lui finançaient sa pratique en loisir. Son père vient de passer chef régional d’une entreprise et touche près de 2 900 euros. Sa mère est assistante sociale auprès de personnes âgées pour 2 100 euros par mois et se situe dans le sixième décile. Maintenant, il se paye lui-même ses études qui sont, selon lui, très coûteuses. « Aujourd’hui, il faut compter en tout 8000 euros pour passer le permis et près de 150 € le vol une fois que tu as passé ce permis. On ne va pas se mentir, c’est une pratique qui coûte très très cher. »
Comme lui, Martin Nobileau, 20 ans, ambitionne de devenir pilote de ligne. Originaire d’une famille aisée résidant en région parisienne, ses parents sont ingénieur⸱e⸱s. Dès la classe de seconde, iels lui ont offert des cours de vol. Ses parents font partie du dernier décile de la population mais ont choisi d’étaler la pratique de leur enfant pour limiter les coûts. En effet, 40 heures de vol minimum sont nécessaires pour l’obtention du permis. A 200 euros de l’heure de leçon, les parents ont donc déboursé près de 8 000 euros, à raison d’une à deux séances par mois.
Des heures et cours de vol trop onéreux pour qu’une personne aux revenus modestes puisse ambitionner de devenir pilote. « Tout le monde ne peut pas devenir un⸱e vrai⸱e pilote car il faudrait voler tous les mois, pas une ou deux fois par an pour se faire plaisir. Je n’ai jamais vu de personnes modestes à l’aéroclub, seulement des quinquagénaires aisé·e·s », explique Martin. Pas de démocratisation en vue, Martin dénonce des « aides extrêmement limitées », la plus réputée ne couvre que 300 euros de frais de cours… A peine 2 heures sur une formation de 40 heures.

Equitation, golf, aviation, ski… Au premier abord, ces sports posent des questions de financements. L’équitation est certes un sport très pratiqué, mais élitiste : toustes les cavaliers⸱ères licencié⸱e⸱s ne peuvent pas se permettre, ou ne ressentent pas forcément l’envie, de pratiquer en compétition. Aussi, l’aventure n’est pas la même si l’on possède ou non son propre cheval. Dès lors qu’on devient propriétaire, il est possible de sortir du côté business que revêt parfois l’équitation.
Pour le golf, il est possible pour les enfants de jouer à bas coût leurs premières années mais, dès qu’il est question de progresser ou de faire de la compétition, les coûts se multiplient. Les frais de matériel notamment sont inabordables pour la plupart des Français·es.
Enfin, l’aviation est inaccessible pour les personnes aux revenus modestes : la pratique dans son intégralité est très onéreuse et les aides sont rares. Pourtant, chacune de ces pratiques s’est défendue bec et ongle contre sa réputation de sport de riche. Certain·e·s sportif·ve·s semblent pâtir de la réputation de leur pratique, mais constituent à être un nouveau moteur de démocratisation des sports stéréotypés élitistes.
</p>
