<p> Maëlle Winona n’aurait jamais pensé que faire du rugby en tant que femme aurait été si compliqué. Cette ancienne Parisienne joue au rugby depuis cinq ans. Après un déménagement, elle s’est installée à Lannion. Mais, surprise, elle n’a trouvé aucun club de rugby féminin dans la ville. Si, auparavant, elle n’avait aucun problème pour jouer en équipe à Paris, la situation est bien différente dans les Côtes d’Armor. La jeune femme de 28 ans s’est donc renseignée auprès du coach lannionnais de l’équipe masculine. Selon lui,  aucune section féminine n'est en projet avant au moins deux ans. Michel Lanchec, le directeur des sports de la ville de Lannion, va même plus loin : <em>« Aucune équipe féminine n’est prévue pour les années à venir pour l’ensemble des sports »</em>. Impatiente de retrouver le ballon ovale, Maëlle s’est donc inscrite au club de Saint-Brieuc, la section féminine la plus proche de chez elle.
</p>

<p> Ce club a été créé par Antoine Lemasson en 2015, pour faciliter l’accès aux femmes qui veulent jouer au rugby. <em>« C’est le seul club 100% féminin au niveau départemental. Aujourd’hui, j’ai des joueuses qui viennent de Paimpol, Guingamp, Loudéac, Rennes et même Pontivy »</em>. Le cas de Maëlle Winona n’est donc pas isolé. Les coureuses cyclistes rencontrent les mêmes difficultés. Là aussi, il n’existe aucune équipe féminine dans les Côtes-d’Armor, et encore moins à Lannion. Seul celui de Vern, en Ille-et-Vilaine, accueille des femmes qui souhaitent rouler. C’est d’ailleurs le seul de la région. Les sportives doivent donc être prêtes à traverser la Bretagne pour les courses du week-end.
</p>

<h3 class="inter"> Traverser le département pour faire du sport </h3>

<p>
	Pour s’entrainer en équipe, il faut être prête à traverser le département, et parfois la région, pour courir ou jouer. Maëlle Winona en sait quelque chose. Deux fois par semaine, elle roule une heure quarante-cinq pour se rendre aux entrainements. <em>« Je suis la plus téméraire du groupe, j’ai signé ma licence malgré les kilomètres »</em>, explique cette sportive acharnée. Le défi est le même pour Gabrielle Rimasson. Cycliste depuis douze ans, la jeune femme courait avec les Breizh Ladies, une équipe régionale féminine créée pour rassembler l’ensemble des Bretonnes de haut niveau. Elle a ensuite intégré l’US Vern, équipe régionale d’Ille-et-Vilaine, à côté de chez elle. <em>« C'est le problème dans le cyclisme : quand on est une femme et qu'on débute, il faut être prête à traverser la Bretagne »</em>, se désole la passionnée de cyclisme. Lorsqu’elle était plus jeune, Gabrielle Rimasson parcourait la région pour la course du week-end. Élevée dans une famille de cyclistes, ses proches suivaient le rythme. Mais ce n’est pas le cas de toutes les petites filles. Certaines se découragent ; la faute aux trajets trop longs, pour les athlètes comme pour leurs parents. Cette contrainte supplémentaire affecte le monde du cyclisme féminin. Si les débutantes ne font pas de courses, elles ne pourront jamais progresser et atteindre un niveau supérieur. Les clubs ne prennent donc pas le temps de créer des sections féminines, estimant qu'il n’existe pas de coureuses de haut niveau. C’est donc un cercle vicieux pour les passionnés de vélo et les structures d’encadrement.
</p>

<h3 class="inter"> Pas de mixité à Lannion </h3>

<p>
	En plus de devoir prendre la route pour rejoindre leurs coéquipières, les coureuses ne bénéficient pas de la reconnaissance attendue. À niveau sportif égal, le statut n’est pas le même. Une centaine d’hommes sont professionnels alors que seules une dizaine de femmes parviennent à faire du cyclisme leur métier. Pire : leur métier non reconnu car leur contrat n’indique pas le statut de professionnelle. Elles sont toujours considérées comme amatrices par la fédération française de cyclisme. Or, dans tous les sports, le statut détermine en partie la rémunération.  L’écart se creuse entre femmes et hommes. Seule l’équipe nationale de la Française des Jeux (FDJ) rémunère ses coureuses. Pour les hommes, c’est automatique. <em> « On n’est pas égalitaires. Et c’est un vrai problème car on ne peut pas vivre de notre passion comme les hommes »</em>, témoigne Gabrielle Rimasson. Face à ce constat, l’association française des coureuses cyclistes a vu le jour en 2019. <em>« On a voulu se réunir pour avoir plus de poids face aux hommes. Toutes les coureuses de haut niveau ont adhéré »</em>. L’association veut développer les courses féminines et faire connaître ce sport. Selon Typhaine Laurance, l’une des rares cyclistes professionnelles de France, le sport manque de médiatisation. Un discours qui est partagé par l’ensemble des coureuses.
</p>

<div class="container-wrapper-genially" style="position: relative; min-height: 400px; max-width: 100%;"><video class="loader-genially" autoplay="autoplay" loop="loop" playsinline="playsInline" muted="muted" style="position: absolute;top: 45%;left: 50%;transform: translate(-50%, -50%);width: 80px;height: 80px;margin-bottom: 10%"><source src="https://static.genial.ly/resources/panel-loader-low.mp4" type="video/mp4" />Your browser does not support the video tag.</video><div id="5fff0b339450fe0cfab7b3f8" class="genially-embed" style="margin: 0px auto; position: relative; height: auto; width: 100%;"></div></div><script>(function (d) { var js, id = "genially-embed-js", ref = d.getElementsByTagName("script")[0]; if (d.getElementById(id)) { return; } js = d.createElement("script"); js.id = id; js.async = true; js.src = "https://view.genial.ly/static/embed/embed.js"; ref.parentNode.insertBefore(js, ref); }(document));</script>
</div>

<p>Ces multiples obstacles poussent ces femmes à se battre pour leur passion. Elles espèrent ainsi développer davantage de sections féminines en France. Et cela d’autant plus que les problèmes de mixité ne concernent pas uniquement dans le milieu du cyclisme, . Le rugby rencontre les mêmes difficultés, comme en témoigne l’expérience de Maëlle Winona. Si l’athlète n’a pas trouvé de club à Lannion, la ville ne semble pas préoccupée par ce problème. Pour le coach du club masculin lannionnais, les femmes ne sont pas intéressées par le rugby et il n’y aurait pas de demande à Lannion. Pourtant 21 femmes sont licenciées à Saint Brieuc. Les femmes seraient-elles donc les grandes oubliées des clubs et de la municipalité ? <em>« Le club de rugby m’avait demandé des financements pour des vestiaires pour les femmes il y a quelques années. Je pensais donc qu’il y avait une équipe féminine. Apparemment ce n’est pas le cas »</em>, se défend le directeur des sports de Lannion.
</p>

<p> Ce manque d'investissement n'est pas forcément la règle. Dans d'autres départements, le sport féminin est l'objet de davantage d'attention.
</p>

<p>À Manosque, dans les Alpes de Hautes Provence, il existe plusieurs équipes féminines. Qu’il s’agisse de handball, rugby, natation, ou encore en football, le choix est varié pour cette petite ville qui compte le même nombre d’habitants. Pourtant, le directeur des sports se réjouit de la création d’un club de football féminin… il y a 3 ans. Avec le basket, ce sont les deux seuls sports avec une équipe exclusivement féminine qui existent. Les sportives qui militent pour l'extension de l’offre de clubs féminins ne doutent pas du succès qu’auraient ces clubs. La demande est là, il ne reste qu'à la prendre en compte.
</p>
