<p> 
À la différence des jeunes garçons, de nombreuses adolescentes arrêtent toute pratique sportive dès 12 ans, au moment de la puberté. 69% des jeunes filles de 6-11 ans font du sport en club, contre 53% chez les 12-17 ans. C’est ce qui ressort de l’étude de l’Institut de recherche biomédicale et d'épidémiologie du sport (Irmes) concernant la pratique sportive des femmes, ces cinq dernières années. Lucille, 20 ans, est l’une d’elle. Elle a pratiqué la gymnastique acrobatique avant d’intégrer une section sportive dans un lycée rennais. Alors qu’elle a 14 ans, son club ferme, mais elle ne se sent pas légitime à reprendre la gymnastique ailleurs. Le passage d’une activité sportive intensive à une inactivité totale a eu des conséquences sur le physique et le moral de la jeune fille. Son estime d’elle-même dégradée, elle n’a pas réussi à se remettre à la gymnastique. <em> « J’étais paralysée par la peur du regard des autres et des injonctions physiques qu’on impose aux filles à l’adolescence. »</em></p>
<br>
<p>Même constat pour Kim. Elle a 15 ans lorsque son entraîneur de basket dans un petit club d’Ille-et-Vilaine est licencié à cause de réductions budgétaires. <em>« Ils n’avaient plus d’intérêt pour nous, je ne me voyais pas m’intégrer à un autre club. J’avais aussi le sentiment de ne pas être à la hauteur pour commencer un nouveau sport à 15 ans, de devoir me réintégrer à une équipe et d’être un poids pour le club. »</em></p>

<p>David Le Breton est professeur de sociologie et anthropologie à l'université de Strasbourg et membre du Laboratoire Cultures et Sociétés en Europe au CNRS. Il a écrit une trentaine de livres, dont Anthropologie du corps et modernité. Il y explique que <em>« la dimension genrée de nombreuses pratiques sociales peut grandement expliquer cet écart dans la pratique sportive ».</em> Le terme de socialisation genrée désigne un processus par lequel les enfants intègrent les attentes sociales, les attitudes et les comportements traditionnellement construits comme associés aux garçons et aux filles. </p>
<p> Les théories ou philosophies dites <em>« du care »</em> trouvent leur origine dans une étude publiée par Carol Gilligan en 1982 aux Etats-Unis. Celle-ci met en évidence, à travers une enquête en psychologie morale, que les critères de décision morale ne sont pas les mêmes chez les hommes et chez les femmes. Par conséquent, les femmes ont plus de facilités que les hommes dans leurs relations interpersonnelles, et plus d’aisance pour développer les interactions sociales. C’est à partir de cette observation que Gilligan établit le nouveau paradigme moral <em>« du care »</em> comme, <em>" souci prioritaire des rapports avec autrui".</em> Les femmes apprendraient tôt à être davantage attentives aux autres, à leurs responsabilités sociales et seraient donc plus facilement bloquées par le regard de leurs semblables. Ces notions sociologiques corroborent un sentiment observé chez certaines jeunes filles, un blocage vis-à-vis du regard des autres, ou la peur d’être un frein à l’équipe ou au club. Mais d’autres exemples d’injonctions différenciées par le genre existent. L’attente sociale d’un niveau scolaire plus élevé chez les filles peut induire la priorisation des résultats scolaires, en dépit de l’activité sportive. 
</p> 
				
<h3 class="inter"> Réussite scolaire, les étudiantes sous pression ? </h3>
				
<p> 
Certaines jeunes filles se sentent dans l’obligation de choisir entre étude et sport, à cause de la pression sociale qui pèse sur elles. <em>« Elles arrêtent l’année du bac avec la pression. Puis le sésame en poche, elles vont dans d’autres clubs. C’est le lot de tous les petits clubs bretons de perdre les athlètes que l’on a formées, quand elles partent dans les études supérieures »</em>, souligne Pierre Paris, président du club d’athlétisme de Lannion. Estimant qu’il s’agit plutôt d’un problème d’agenda que d’intégration dans la pratique sportive, le club n’a pas trouvé nécessaire de mettre en place des actions pour éviter cette situation. <em>« Quelques-unes vont reprendre après leurs études, une fois qu’elles auront un travail stable »</em>, ajoute-t-il. Cependant, beaucoup de jeunes filles ne reprennent pas le sport, alors que le bac est passé et les études supérieures entamées. </p>
<p>
C’est le cas de Louise, triple championne de France de gymnastique. Après l’intégration de la section sportive au lycée Bréquigny à Rennes, elle a dû arrêter la gymnastique pour se concentrer sur ses études : <em>« La pression familiale m’a conduit à aller en filière scientifique. Je pense que l'on en attend plus des jeunes filles qu'elles réussissent scolairement. Je voyais mes amis continuer le sport étude en Football ou Judo, sans jamais se poser la question de la priorité des cours »</em>. Lorsqu'elle arrive à l'université, la jeune femme ne reprend pas le sport, malgré un emploi du temps allégé. Les conséquences de l'arrêt d'une pratique intensive sont douloureuses. <em>« Le temps avait passé, je n'étais plus capable de faire les mêmes choses, mon corps avait changé. Je le regrette, mais je n’ai jamais repris depuis. » </em>

</p> 

<h3 class="inter"> Bouleversement hormonaux et changement des corps, fatalité ? </h3>

<div style="width: 100%;"><div style="position: relative; padding-bottom: 56.25%; padding-top: 0; height: 0;"><iframe frameborder="0" width="1200px" height="675px" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://view.genial.ly/5fff4c49f7609f0cf7add8dc" type="text/html" allowscriptaccess="always" allowfullscreen="true" scrolling="yes" allownetworking="all"></iframe> </div> </div>
<br>
<br>
<div id="legende">Source infographie : chiffres étude Irmes et l'association Attitude Prévention </div>
<br>
<p>
Mathilde L’Azou, community manager pour l’équipe cycliste Cofidis, était athlète jusqu’à l’âge de 16 ans. L’arrêt du sport en club n’a pas été causé par la disparition de sa passion pour le sport. L’arrivée de la puberté, et en particulier l’apparition des règles, l’ont contrainte dans sa pratique. Comme nombre de jeunes femmes, la puberté est un déluge hormonal qui entraîne des changements physiques. <em>« Assez rapidement, les règles me paralysaient cinq jours par mois. Les formateurs sont des bénévoles, ils ne sont pas formés pour coacher des adolescentes. Bah non en fait, ce ne sont pas seulement des règles. Cela peut en effet représenter de réelles difficultées dans le sport, qui nécessitent un accompagnement de la part des professionnels du sport »</em>, ajoute-t-elle avec conviction. </p>
<p>Les menstruations abondantes chez certaines jeunes filles, appelées ménorragies, les empêchent de pratiquer une activité physique sur une longue durée. Des aménagements sont nécessaires afin de s’adapter à la fatigue et aux carences liées à la perte de sang. Parfois les jeunes filles et les femmes souffrent aussi d’un syndrome prémenstruel (SPM), qui est défini comme l’apparition de symptômes cycliques très perturbants pour la vie quotidienne. En effet, <em>« on estime que 4 à 5% des femmes âgées de 15 à 45 ans qui souffrent de SPM devront avoir recours à un traitement médicamenteux ou autre »</em>, <a href="https://www.passionsante.be/index.cfm?fuseaction=art&art_id=13663">indique le site santé belge Passionsanté.</a>  Près de 90% des femmes déclarent se sentir dans un état physique ou psychique différent durant les jours qui précèdent les règles, sans que l’on parle de SPM. </p>
<p>La pilule contraceptive est majoritairement le premier contraceptif utilisé chez les jeunes filles au début de leur vie sexuelle. Elle peut aussi être prescrite tôt afin de réguler l’arrivée des règles, parfois dès 12 ans, pour atténuer la douleur et le bouleversement hormonal que provoque la puberté. Mais elle peut aussi engendrer des effets indésirables, comme la prise de poids. <em>« La prise de poids qui survient parfois avec la prescription d’une pilule contraceptive est l’une des principales craintes des jeunes filles, en particulier pour les sportives »</em>, ajoute Annie Heslan, gynécologue à Rennes. <em>« L'athlétisme, c’est le culte de la maigreur. Celle qui court le plus vite, c’est celle qui est maigre. À l'adolescence, on prend de la masse graisseuse, encore plus parfois avec les effets secondaires de la pilule contraceptive »</em>, témoigne avec ferveur Mathilde L’Azou. Le manque d'information au sujet de la puberté semble ainsi également être un frein pour les jeunes femmes qui subissent ces changements, et qui peinent à adapter leur pratique sportive à ces derniers. </p>
<p>Ces propos viennent rejoindre une idée avancée par David Le Breton : <em>« La temporalité est différente chez les femmes, alors qu’il y a une continuité chez les hommes. Les femmes vivent des événements qui les transforment. En fonction de l’éducation, ils peuvent être plus ou moins violents. »</em> Les femmes elles-mêmes ne sont pas toujours préparées par leurs aînées à ces bouleversements, raconte le sociologue. Ce qui conduit une partie d’entre elles à développer un sentiment d’illégitimité, également accrue par certains codes physiques dans le sport. 
</p>
<h3 class="inter"> Le sport, un espace de domination masculine </h3>
<p>
L’intégration dans le club ou l’équipe est aussi un obstacle, selon les jeunes filles interrogées. Comme tout espace défini par des interactions sociales, il peut être approprié par les hommes. Le sport devient, dans les représentations sociales, un champ défini par la concurrence, la performance. Ce modèle de la compétition ne suffit pas à englober les diverses socialisations des hommes. Mais cela influe tout de même sur le sentiment d'illégitimité des femmes, accru par la socialisation genrée.  Alors que les représentations sociales associent souvent la masculinité au besoin de se défouler, la féminité est quant à elle plutôt associée au calme. Le milieu social dans lequel les jeunes femmes vont pratiquer leur activité sportive va alors modifier leur perception de la discipline et des interactions sociales qu’on y associe. Certains sports ou clubs seront alors plus favorables à leur épanouissement personnel que d’autres.</p>
<p> A ces processus sociologiques, s’ajoute une dimension environnementale où les espaces publics sont souvent dominés par les hommes. <a href="http://www.popsu.archi.fr/popsu-europe/themes/le-pieton-dans-la-ville-l-espace-public-partage">Toutefois, les politiques mises en place dans les espaces urbains</a> visent à les contourner, en offrant un espace dédié à la pratique sportive mixte.
 </p>
<p>Dans les faits, selon David Le Breton, une fille est toujours un peu une intruse  pour les occupants masculins des barres de tractions et autres structures de <em>« street workout »</em> : <em>« Dans un nouveau contexte fortement marqué par les exigences en termes de développement durable, la marche est désormais érigée en pivot des politiques de partage de l'espace public. »</em> . Ainsi, les sports privilégiés par les femmes sont notamment des activités qui ne nécessitent pas un espace ou du matériel partagé : <a href="https://www.assurance-prevention.fr/donnees-chiffrees/activite-physique-sportive-femmes">la marche (22 %), le vélo (16 %) et la course à pied (16 %).</a>
 </p>
<p>Depuis quelques années, les pouvoirs publics multiplient les campagnes de prévention et de promotion de l’activité sportive, comme le site web manger-bouger.fr. Elles concernent les jeunes, et en particulier les adolescentes. Les autorités soulèvent des enjeux politiques, de libération des femmes, et de santé publique autour de la pratique sportive. <a href="https://www.sports.gouv.fr/pratiques-sportives/sport-sante-bien-etre/bienfaits-du-sport/Jeunes">Le ministère chargé des sports a bien pris la mesure de ces enjeux.</a> En 2013, il a conseillé que <em>« les enfants et jeunes gens de 5 à 17 ans devraient accumuler au moins 60 minutes par jour d’activité physique d’intensité modérée à soutenue »</em></p>
<p>En pratique, les jeunes, et particulièrement les jeunes filles, sont loin d’avoir une pratique aussi régulière. Seulement, les causes diverses de l’exclusion féminine trouvent surtout leur origine dans les modes de socialisation genrée, ce qui ne permet pas aux institutions d’atteindre leurs objectifs avec des campagnes de communication. A l'heure de l’omniprésence des réseaux sociaux, les jeunes filles se soucient  plus que jamais de leur image, très soumise aux jugements de leurs pairs. Cependant des mouvements de solidarité y naissent et pourraient bien briser ce plafond de verre, et changer les injonctions patriarcales qui pèsent sur les femmes, leurs règles, leurs formes. 
</p>